namespace CatalogSalfa.Entities
{
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse); 
    public class ActivityFinancial
    {
        public double project { get; set; }
        public double wbsId { get; set; }
        public double activity { get; set; }
        public double activityId { get; set; }
        public double earnedValueCost { get; set; }
        public double plannedValueCost { get; set; }
        public double scheduleVariance { get; set; }
        public double plannedExpenseCost { get; set; }
        public double actualThisPeriodLaborCostProject { get; set; }
        public double plannedLaborCost { get; set; }
        public double plannedLaborCostProject { get; set; }
        public double plannedMaterialCost { get; set; }
        public double plannedMaterialCostProject { get; set; }
        public double plannedNonLaborCost { get; set; }
        public double plannedNonLaborCostProject { get; set; }
        public double plannedTotalCost { get; set; }
        public double plannedTotalCostProject { get; set; }
        public double remainingExpenseCost { get; set; }
        public double remainingLaborCost { get; set; }
        public double remainingLaborCostProject { get; set; }
        public double remainingMaterialCost { get; set; }
        public double remainingMaterialCostProject { get; set; }
        public double remainingNonLaborCost { get; set; }
        public double remainingNonLaborCostProject { get; set; }
        public double remainingTotalCost { get; set; }
        public double remainingTotalCostProject { get; set; }
        public double actualExpenseCost { get; set; }
        public double actualLaborCost { get; set; }
        public double actualLaborCostProject { get; set; }
        public double actualMaterialCost { get; set; }
        public double actualMaterialCostProject { get; set; }
        public double actualNonLaborCost { get; set; }
        public double actualNonLaborCostProject { get; set; }
        public double actualTotalCost { get; set; }
        public double actualTotalCostProject { get; set; }
        public double atCompletionExpenseCost { get; set; }
        public double atCompletionLaborCost { get; set; }
        public double atCompletionLaborCostProject { get; set; }
        public double atCompletionMaterialCost { get; set; }
        public double atCompletionMaterialCostProject { get; set; }
        public double atCompletionNonLaborCost { get; set; }
        public double atCompletionNonLaborCostProject { get; set; }
        public double atCompletionTotalCost { get; set; }
        public double atCompletionTotalCostProject { get; set; }
        public double blplannedExpenseCost { get; set; }
        public double blplannedLaborCost { get; set; }
        public double blplannedMaterialCost { get; set; }
        public double blplannedNonLaborCost { get; set; }
        public double blplannedTotalCost { get; set; }
        public double accountingVariance { get; set; }
        public double expenseCostVariance { get; set; }
        public double laborCostVariance { get; set; }
        public double materialCostVariance { get; set; }
        public double nonLaborCostVariance { get; set; }
        public double totalCostVariance { get; set; }
        public double actualThisPeriodLaborCost { get; set; }
        public double actualThisPeriodNonLaborCost { get; set; }
        public double actualThisPeriodNonLaborCostProject { get; set; }
        public double actualThisPeriodMaterialCost { get; set; }
        public double actualThisPeriodMaterialCostProject { get; set; }
        public double actualThisPeriodTotalCost { get; set; }
        public double actualThisPeriodTotalCostProject { get; set; }
        public double priorActualLaborCost { get; set; }
        public double priorActualLaborCostProject { get; set; }
        public double priorActualNonLaborCost { get; set; }
        public double priorActualNonLaborCostProject { get; set; }
        public double priorActualMaterialCost { get; set; }
        public double priorActualMaterialCostProject { get; set; }
        public double priorActualTotalCost { get; set; }
        public double priorActualTotalCostProject { get; set; }
        public double budgetAtCompletion { get; set; }
        public double budgetAtCompletionProject { get; set; }
        public double plannedValueCostProject { get; set; }
        public double earnedValueCostProject { get; set; }
        public double scheduleVarianceProject { get; set; }
        public double varCost { get; set; }
        public double varCostProject { get; set; }
        public double estimateToCompletionCost { get; set; }
        public double estimateToCompletionCostProject { get; set; }
        public double estimateAtCompletionCost { get; set; }
        public double estimateAtCompletionCostProject { get; set; }
        public double atCompletionVariance { get; set; }
        public double atCompletionVarianceProject { get; set; }
        public double earnedValueLaborUnits { get; set; }
        public double scheduleVarianceIndex { get; set; }
        public double costVarianceLaborUnits { get; set; }
        public double costVarianceIndex { get; set; }
        public double costVarianceLaborUnitsIndex { get; set; }
        public double schedulePerformanceIndex { get; set; }
        public double toCompletePerformanceIndex { get; set; }
        public DateTime updateDate { get; set; }
    }

    public class Activity
    {
        public double workManagerTaskUnplannedCount { get; set; }
        public string constradoubleType { get; set; }
        public double calendar { get; set; }
        public double sequenceNumber { get; set; }
        public string owner { get; set; }
        public double projectId { get; set; }
        public string projectCode { get; set; }
        public string startDate { get; set; }
        public double wbsId { get; set; }
        public string workspaceCode { get; set; }
        public double activityId { get; set; }
        public List<object> activityUncertadoubleies { get; set; }
        public List<object> codeValuesActivity { get; set; }
        public string activityCode { get; set; }
        public List<object> configuredFields { get; set; }
        public string calendarName { get; set; }
        public string percentCompleteWeightedBy { get; set; }
        public string finishDate { get; set; }
        public double actualDuration { get; set; }
        public double remainingDuration { get; set; }
        public double plannedDuration { get; set; }
        public double recordCount { get; set; }
        public double plannedLaborUnits { get; set; }
        public double actualLaborUnits { get; set; }
        public double remainingLaborUnits { get; set; }
        public double scopePercentComplete { get; set; }
        public double performancePercentComplete { get; set; }
        public bool critical { get; set; }
        public bool starred { get; set; }
        public double schedulePercentComplete { get; set; }
        public string actualStart { get; set; }
        public string remainingFinish { get; set; }
        public string remainingStart { get; set; }
        public string plannedStart { get; set; }
        public string plannedFinish { get; set; }
        public string remainingLateStart { get; set; }
        public string remainingLateFinish { get; set; }
        public double atCompletionDuration { get; set; }
        public double unitsPercentComplete { get; set; }
        public string activityName { get; set; }
        public double costPerformanceIndexLaborUnits { get; set; }
        public ActivityFinancial activityFinancial { get; set; }
        public bool drivingPath { get; set; }
        public double actualThisPeriodNonLaborUnits { get; set; }
        public double actualThisPeriodLaborUnits { get; set; }
        public string earlyFinish { get; set; }
        public string earlyStart { get; set; }
        public string lateFinish { get; set; }
        public string lateStart { get; set; }
        public string secondaryConstradoubleType { get; set; }
        public double plannedNonLaborUnits { get; set; }
        public double actualNonLaborUnits { get; set; }
        public double remainingNonLaborUnits { get; set; }
        public double priorActualLaborUnits { get; set; }
        public double priorActualNonLaborUnits { get; set; }
        public double freeFloat { get; set; }
        public double totalFloat { get; set; }
        public string activityStatus { get; set; }
        public string percentCompleteType { get; set; }
        public double physicalPercentComplete { get; set; }
        public string durationType { get; set; }
        public string activityType { get; set; }
        public string activityPriority { get; set; }
        public double atCompletionLaborUnits { get; set; }
        public double atCompletionNonLaborUnits { get; set; }
        public double durationPercentComplete { get; set; }
        public double durationPercentOfPlanned { get; set; }
        public double laborUnitsCompletePercent { get; set; }
        public double nonLaborUnitsCompletePercent { get; set; }
        public double activityPercentComplete { get; set; }
        public string resourceCodeList { get; set; }
        public string resourceNameList { get; set; }
        public double remainingFloat { get; set; }
        public string activityWorkManagerTaskDateStatus { get; set; }
        public string activityWorkManagerTaskStatus { get; set; }
        public bool activityWorkManagerTaskStatusIndicator { get; set; }
        public double workManagerTaskCount { get; set; }
        public double workManagerTaskPlannedOutsideCount { get; set; }
        public double workManagerTaskPlannedNotCompleteCount { get; set; }
        public double workManagerTaskPlannedCompleteCount { get; set; }
        public bool programMilestone { get; set; }
        public double atCompletionBudgetLaborUnits { get; set; }
        public double plannedValueLaborUnits { get; set; }
        public double earnedValueLaborUnits { get; set; }
        public double scheduleVarianceLaborUnits { get; set; }
        public double scheduleVarianceIndex { get; set; }
        public double scheduleVarIndexLaborUnits { get; set; }
        public double costVarianceLaborUnits { get; set; }
        public double costVarianceIndex { get; set; }
        public double costVarianceLaborUnitsIndex { get; set; }
        public double schedulePerformanceIndex { get; set; }
        public double schedulePerfIndexLaborUnits { get; set; }
        public double costPerformanceIndex { get; set; }
        public double estimateToCompletionLaborUnits { get; set; }
        public double toCompletePerformanceIndex { get; set; }
        public double estimateAtCompletionLaborUnits { get; set; }
        public double varianceAtCompletionLaborUnits { get; set; }
        public DateTime updateDate { get; set; }
    }


}